# Generated by Django 5.2.8 on 2025-11-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование частной школы')),
                ('has_state_order', models.BooleanField(default=False, verbose_name='Размещен госзаказ')),
                ('license_date', models.DateField(blank=True, null=True, verbose_name='Дата получения лицензии')),
                ('project_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Проектная мощность')),
                ('students_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего учащихся')),
                ('students_primary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во учащихся начального уровня')),
                ('students_basic', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во учащихся основного среднего уровня')),
                ('students_general', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во учащихся общего среднего уровня')),
                ('director_education', models.CharField(blank=True, max_length=255, verbose_name='Образование директора')),
                ('director_teacher_category', models.CharField(blank=True, max_length=255, verbose_name='Пед. категория директора')),
                ('director_manager_category', models.CharField(blank=True, max_length=255, verbose_name='Категория как руководителя')),
                ('director_total_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общий стаж директора (лет)')),
                ('director_position_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж на данной позиции (лет)')),
                ('director_is_founder', models.BooleanField(default=False, verbose_name='Директор является учредителем')),
                ('teachers_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего педагогов')),
                ('nf_teacher', models.PositiveIntegerField(blank=True, null=True, verbose_name='педагог')),
                ('nf_moderator', models.PositiveIntegerField(blank=True, null=True, verbose_name='педагог-модератор')),
                ('nf_expert', models.PositiveIntegerField(blank=True, null=True, verbose_name='педагог-эксперт')),
                ('nf_researcher', models.PositiveIntegerField(blank=True, null=True, verbose_name='педагог-исследователь')),
                ('nf_master', models.PositiveIntegerField(blank=True, null=True, verbose_name='педагог-мастер')),
                ('old_category_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во педагогов со старой категорией')),
                ('no_category_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во педагогов без категории')),
                ('external_parttimers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во внешних совместителей')),
                ('own_typical', models.BooleanField(default=False, verbose_name='Собственное типовое здание')),
                ('own_adapted', models.BooleanField(default=False, verbose_name='Собственное приспособленное здание')),
                ('rented_typical', models.BooleanField(default=False, verbose_name='Арендованное типовое здание')),
                ('rented_adapted', models.BooleanField(default=False, verbose_name='Арендованное приспособленное здание')),
                ('gym_own', models.BooleanField(default=False, verbose_name='Собственный спортивный зал')),
                ('gym_rented_lt_1000', models.BooleanField(default=False, verbose_name='Арендованный спортзал (до 1000 м²)')),
                ('gym_rented_gt_1000', models.BooleanField(default=False, verbose_name='Арендованный спортзал (более 1000 м²)')),
                ('has_textbook_set', models.BooleanField(default=False, verbose_name='Комплект учебников на каждого ученика')),
                ('has_fiction_fund', models.BooleanField(default=False, verbose_name='Библиотечный фонд художественной литературы')),
                ('has_computer_classes', models.BooleanField(default=False, verbose_name='Наличие компьютерных классов')),
                ('has_cctv', models.BooleanField(default=False, verbose_name='Наличие видеонаблюдения')),
                ('has_lab_physics', models.BooleanField(default=False, verbose_name='Модифицированный кабинет физики')),
                ('has_lab_chemistry', models.BooleanField(default=False, verbose_name='Модифицированный кабинет химии')),
                ('has_lab_biology', models.BooleanField(default=False, verbose_name='Модифицированный кабинет биологии')),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Аварийное состояние')),
                ('needs_repair', models.BooleanField(default=False, verbose_name='Требует ремонта')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.district', verbose_name='Район/город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Частная школа',
                'verbose_name_plural': 'Частные школы',
            },
        ),
    ]
