# Generated by Django 5.2.8 on 2025-11-27 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Раздел/блок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел критериев',
                'verbose_name_plural': 'Разделы критериев',
                'ordering': ['inspection_type', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код вида')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование вида проверки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вид проверки',
                'verbose_name_plural': 'Виды проверок',
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код критерия')),
                ('name', models.CharField(max_length=500, verbose_name='Формулировка критерия')),
                ('value_type', models.CharField(choices=[('bool', 'Да/Нет'), ('int', 'Целое число'), ('decimal', 'Число с точкой'), ('text', 'Текст')], default='bool', max_length=10, verbose_name='Тип значения')),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Максимальный балл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterias', to='monitoring.criterioncategory', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='criterioncategory',
            name='inspection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='monitoring.inspectiontype', verbose_name='Вид проверки'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('bin', models.CharField(blank=True, max_length=12, verbose_name='БИН')),
                ('is_private', models.BooleanField(default=False, verbose_name='Частная школа')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.district', verbose_name='Район/город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Организация образования',
                'verbose_name_plural': 'Организации образования',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год проверки')),
                ('date_visit', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В процессе'), ('completed', 'Завершён ДОКСО'), ('approved', 'Утверждён центром')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Итоговый балл')),
                ('comment', models.TextField(blank=True, verbose_name='Общий комментарий/вывод')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.district', verbose_name='Район/город')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Инспектор (ДОКСО)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.region', verbose_name='Регион')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='monitoring.inspectiontype', verbose_name='Вид проверки')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='monitoring.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Проверка (акт)',
                'verbose_name_plural': 'Проверки (акты)',
                'ordering': ['-year', '-date_visit', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Да/Нет')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Целое значение')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Числовое значение')),
                ('value_text', models.TextField(blank=True, verbose_name='Текстовое значение / пояснение')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Баллы по критерию')),
                ('has_violation', models.BooleanField(default=False, verbose_name='Есть нарушение')),
                ('violation_comment', models.TextField(blank=True, verbose_name='Замечания / описание нарушения')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='monitoring.criterion', verbose_name='Критерий')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.inspection', verbose_name='Проверка')),
            ],
            options={
                'verbose_name': 'Результат по критерию',
                'verbose_name_plural': 'Результаты по критериям',
                'unique_together': {('inspection', 'criterion')},
            },
        ),
    ]
