# Generated by Django 5.2.8 on 2025-11-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='acting_head_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО и.о. руководителя'),
        ),
        migrations.AddField(
            model_name='school',
            name='acting_head_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность и.о. руководителя'),
        ),
        migrations.AddField(
            model_name='school',
            name='afterschool_groups_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество групп продленного дня'),
        ),
        migrations.AddField(
            model_name='school',
            name='classrooms_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество кабинетов'),
        ),
        migrations.AddField(
            model_name='school',
            name='complex_school_kindergarten',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комплекс «школа-ясли-сад»'),
        ),
        migrations.AddField(
            model_name='school',
            name='complex_special_school_kindergarten',
            field=models.CharField(blank=True, max_length=50, verbose_name='Специальный комплекс «школа-ясли-сад»'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10-11/13: дистанционно'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_evening',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10-11/13: вечерний класс'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_external',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10-11/13: экстернат'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_fulltime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10-11/13: очно обучаются'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_home',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10-11/13: обучаются на дому'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_oop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10-11/13: с ООП (с перв.нар)'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_shift1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10-11/13: в 1 смену'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_10_11_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Контингент 10-11/13 кл.'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_11_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Контингент 1-11/13 кл.'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1-4: дистанционно'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_evening',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1-4: вечерний класс'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_external',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1-4: экстернат'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_fulltime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1-4: очно обучаются'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_home',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1-4: обучаются на дому'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_oop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1-4: с ООП (с перв.нар)'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_shift1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1-4: в 1 смену'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_1_4_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Контингент 1-4 кл.'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5-9: дистанционно'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_evening',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5-9: вечерний класс'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_external',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5-9: экстернат'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_fulltime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5-9: очно обучаются'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_home',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5-9: обучаются на дому'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_oop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5-9: с ООП (с перв.нар)'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_shift1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5-9: в 1 смену'),
        ),
        migrations.AddField(
            model_name='school',
            name='cont_5_9_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Контингент 5-9 кл.'),
        ),
        migrations.AddField(
            model_name='school',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ведомственная принадлежность'),
        ),
        migrations.AddField(
            model_name='school',
            name='edu_org_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип организации образования'),
        ),
        migrations.AddField(
            model_name='school',
            name='education_duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Продолжительность обучения'),
        ),
        migrations.AddField(
            model_name='school',
            name='education_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='school',
            name='education_levels',
            field=models.CharField(blank=True, max_length=255, verbose_name='По уровням образования'),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='E-mail организации образования'),
        ),
        migrations.AddField(
            model_name='school',
            name='fax',
            field=models.CharField(blank=True, max_length=100, verbose_name='Факс'),
        ),
        migrations.AddField(
            model_name='school',
            name='founders',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основные учредители'),
        ),
        migrations.AddField(
            model_name='school',
            name='has_state_order',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наличие государственного заказа'),
        ),
        migrations.AddField(
            model_name='school',
            name='head_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='school',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='№ дома'),
        ),
        migrations.AddField(
            model_name='school',
            name='kato_ar',
            field=models.CharField(blank=True, max_length=20, verbose_name='kato_ar'),
        ),
        migrations.AddField(
            model_name='school',
            name='kato_np',
            field=models.CharField(blank=True, max_length=20, verbose_name='kato_np'),
        ),
        migrations.AddField(
            model_name='school',
            name='kato_reg',
            field=models.CharField(blank=True, max_length=20, verbose_name='kato_reg'),
        ),
        migrations.AddField(
            model_name='school',
            name='legal_address_kz',
            field=models.TextField(blank=True, verbose_name='Адрес юридический на казахском'),
        ),
        migrations.AddField(
            model_name='school',
            name='legal_address_ru',
            field=models.TextField(blank=True, verbose_name='Адрес юридический на русском'),
        ),
        migrations.AddField(
            model_name='school',
            name='legal_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AddField(
            model_name='school',
            name='license_authority',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кем выдана лицензия на право образовательной деятельности'),
        ),
        migrations.AddField(
            model_name='school',
            name='license_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи лицензии'),
        ),
        migrations.AddField(
            model_name='school',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер лицензии'),
        ),
        migrations.AddField(
            model_name='school',
            name='locality',
            field=models.CharField(blank=True, max_length=255, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Расположен'),
        ),
        migrations.AddField(
            model_name='school',
            name='name_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование организации каз'),
        ),
        migrations.AddField(
            model_name='school',
            name='name_kz_full',
            field=models.TextField(blank=True, verbose_name='Наименование организации каз полное'),
        ),
        migrations.AddField(
            model_name='school',
            name='name_ru_full',
            field=models.TextField(blank=True, verbose_name='Наименование организации рус полное'),
        ),
        migrations.AddField(
            model_name='school',
            name='np_part_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование составной части населенного пункта'),
        ),
        migrations.AddField(
            model_name='school',
            name='np_part_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип составной части населенного пункта'),
        ),
        migrations.AddField(
            model_name='school',
            name='open_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата открытия'),
        ),
        migrations.AddField(
            model_name='school',
            name='org_kinds',
            field=models.CharField(blank=True, max_length=255, verbose_name='Виды организации'),
        ),
        migrations.AddField(
            model_name='school',
            name='os_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID из ОСО'),
        ),
        migrations.AddField(
            model_name='school',
            name='ownership_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='Форма собственности'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сотовый телефон'),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_work',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рабочий телефон'),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_index',
            field=models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='school',
            name='shifts_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество смен'),
        ),
        migrations.AddField(
            model_name='school',
            name='special_classes_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество спец классов'),
        ),
        migrations.AddField(
            model_name='school',
            name='start_grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='С какого класса ведется обучение'),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='school',
            name='study_week',
            field=models.CharField(blank=True, max_length=50, verbose_name='Учебная неделя'),
        ),
        migrations.AddField(
            model_name='school',
            name='teaching_language',
            field=models.CharField(blank=True, max_length=255, verbose_name='Язык обучения'),
        ),
        migrations.AddField(
            model_name='school',
            name='territory',
            field=models.CharField(blank=True, max_length=255, verbose_name='Территориальная принадлежность'),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование организации (кратко)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.region', verbose_name='Область'),
        ),
    ]
