# Generated by Django 5.2.8 on 2025-11-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitoringuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringuser',
            name='role',
            field=models.CharField(choices=[('center', 'Республиканский центр'), ('inspector', 'Региональный ДОКСО')], default='inspector', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterUniqueTogether(
            name='inspection',
            unique_together={('inspection_type', 'school', 'year')},
        ),
    ]
