# Generated by Django 5.2.8 on 2026-01-19 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_monitoringuser_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ['category', 'parent_id', 'order', 'id'], 'verbose_name': 'Критерий', 'verbose_name_plural': 'Критерии'},
        ),
        migrations.AddField(
            model_name='criterion',
            name='excel_col',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Колонка Excel (1..39)'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='monitoring.criterion', verbose_name='Родительский критерий'),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Код критерия'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='value_type',
            field=models.CharField(choices=[('bool', 'Да/Нет'), ('int', 'Целое число'), ('decimal', 'Число с точкой'), ('text', 'Текст'), ('date', 'Дата')], default='bool', max_length=10, verbose_name='Тип значения'),
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('category', 'code')},
        ),
    ]
