# Generated by Django 5.2.8 on 2026-01-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_criterion_options_criterion_excel_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Утвержден центром (время)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен в центр (время)'),
        ),
    ]
